# Basic workflow from Github Actions
name: CI - Build + Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Manual trigger for testing, REMOVE LATER

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Just check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4 # latest

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      
      # Step 3: Run pytest unit tests
      - name: Run Python unit tests
        run: make unit-test

  full-build-and-integration-test:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code, including submodules
      - name: Checkout repository
        uses: actions/checkout@v4 # latest
        with:
          submodules: 'true' # whisper.cpp

      # Step 2: Run build and test that it works
      - name: Build and Test App
        run: make test